# Setup
title:               Martyn Jones Blog
tagline:             'Tagline goes here'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         ''
url:                 https://martynjones87.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Martyn Jones
  url:               https://twitter.com/thurboman
  email:             martynnjones@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
